---
- name: Copy file from local to remote
  hosts: webservers


  tasks:
    - name: Copying file
      become: true
      ansible.builtin.copy:
        src: /home/vmware/Documents/install_kvm.sh
        dest: /tmp
        owner: vm2
        group: vm2
        mode: "0744"
