---
- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
- name: Start Apache2
  ansible.builtin.service:
    name: apache2
    state: started
- name: Start firewall
  community.general.ufw:
    state: enabled
    policy: allow
- name: Open port Apache2 on firewall
  community.general.ufw:
    rule: allow
    name: Apache
    # port: http
- name: Restart firewall
  ansible.builtin.service:
    name: ufw
    state: restarted
